/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-05-24 13:05:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class pages_002dlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("  <title>Đăng nhập - KFC</title>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Simplified CSS -->\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: #f8f9fa;\r\n");
      out.write("    }\r\n");
      out.write("    .login-container {\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("    .login-card {\r\n");
      out.write("      border-radius: 15px;\r\n");
      out.write("      box-shadow: 0 5px 15px rgba(0,0,0,0.1);\r\n");
      out.write("    }\r\n");
      out.write("    .kfc-logo img {\r\n");
      out.write("      height: 80px;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-kfc {\r\n");
      out.write("      background-color: #e4002b;\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-kfc:hover {\r\n");
      out.write("      background-color: #c10022;\r\n");
      out.write("    }\r\n");
      out.write("    .invalid-feedback {\r\n");
      out.write("      color: #dc3545;\r\n");
      out.write("      font-size: 0.85rem;\r\n");
      out.write("    }\r\n");
      out.write("    .valid-feedback {\r\n");
      out.write("      color: #28a745;\r\n");
      out.write("      font-size: 0.85rem;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container-fluid login-container\">\r\n");
      out.write("    <div class=\"row h-100\">\r\n");
      out.write("      <!-- Left Image Column -->\r\n");
      out.write("      <div class=\"col-lg-6 d-none d-lg-block p-0\">\r\n");
      out.write("        <div class=\"h-100 w-100\" style=\"background-image: url('assets/img/anhdn.jpg'); background-size: cover;\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <!-- Right Form Column -->\r\n");
      out.write("      <div class=\"col-lg-6 d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"w-75\">\r\n");
      out.write("          <div class=\"text-center mb-4\">\r\n");
      out.write("            <img src=\"assets/img/logo1.jpg\" alt=\"KFC Logo\" class=\"mb-3\" style=\"height: 80px;\">\r\n");
      out.write("            <h2 class=\"mb-1\">Đăng nhập hệ thống</h2>\r\n");
      out.write("            <p class=\"text-muted\">Nhập thông tin đăng nhập của bạn</p>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card login-card\">\r\n");
      out.write("            <div class=\"card-body p-4\">\r\n");
      out.write("              <!-- Error Message -->\r\n");
      out.write("              ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("			  <div class=\"alert alert-danger\">\r\n");
      out.write("			    ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("			  </div>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("              \r\n");
      out.write("              <!-- Login Form -->\r\n");
      out.write("              <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dang-nhap\" method=\"post\" class=\"needs-validation\" novalidate>\r\n");
      out.write("                <!-- Full Name -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                  <label class=\"form-label\">Họ và tên</label>\r\n");
      out.write("                  <div class=\"input-group\">\r\n");
      out.write("                    <span class=\"input-group-text\">@</span>\r\n");
      out.write("                    <input type=\"text\" name=\"hoten\" class=\"form-control\" required>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Vui lòng nhập họ tên</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Username -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                  <label class=\"form-label\">Tên đăng nhập</label>\r\n");
      out.write("                  <div class=\"input-group\">\r\n");
      out.write("                    <span class=\"input-group-text\">@</span>\r\n");
      out.write("                    <input type=\"text\" name=\"username\" class=\"form-control\" required>\r\n");
      out.write("                    <div class=\"invalid-feedback\">Vui lòng nhập tên đăng nhập</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Password -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                  <label class=\"form-label\">Mật khẩu</label>\r\n");
      out.write("                  <input type=\"password\" name=\"password\" class=\"form-control\" required>\r\n");
      out.write("                  <div class=\"invalid-feedback\">Vui lòng nhập mật khẩu</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Remember Me -->\r\n");
      out.write("                <div class=\"mb-3 form-check\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"remember\" class=\"form-check-input\" id=\"rememberMe\">\r\n");
      out.write("                  <label class=\"form-check-label\" for=\"rememberMe\">Ghi nhớ tài khoản</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Submit Button -->\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-kfc w-100 py-2\">Đăng nhập</button>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap JS -->\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <!-- Form Validation -->\r\n");
      out.write("  <script>\r\n");
      out.write("  (function () {\r\n");
      out.write("    'use strict'\r\n");
      out.write("    \r\n");
      out.write("    const forms = document.querySelectorAll('.needs-validation')\r\n");
      out.write("    \r\n");
      out.write("    Array.from(forms).forEach(form => {\r\n");
      out.write("      form.addEventListener('submit', event => {\r\n");
      out.write("        if (!form.checkValidity()) {\r\n");
      out.write("          event.preventDefault()\r\n");
      out.write("          event.stopPropagation()\r\n");
      out.write("        }\r\n");
      out.write("        form.classList.add('was-validated')\r\n");
      out.write("      }, false)\r\n");
      out.write("    })\r\n");
      out.write("  })()\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
